# Generated by Django 4.0.2 on 2022-09-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='puzzles/img/%Y/%m/%d')),
                ('price', models.IntegerField(blank=True, default=100)),
                ('counter', models.PositiveIntegerField()),
                ('company', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='katalog.company')),
                ('type', models.ForeignKey(default='3', null=True, on_delete=django.db.models.deletion.CASCADE, to='katalog.typepuzzle')),
            ],
        ),
    ]
