# Generated by Django 4.0.2 on 2022-11-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address_post', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('order', models.CharField(max_length=200)),
                ('is_made', models.BooleanField(default=False)),
            ],
        ),
    ]
